(define (make-segment start-point end-point)
  (cons start-point end-point))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))

(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-point x y)
  (cons x y))

(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))

(define (average x y)
  (/ (+ x y) 2.0))

(define (midpoint-segment segment)
  (let ((ss (start-segment segment))
        (es (end-segment segment)))
    (make-point (average (x-point ss) (x-point es))
                (average (y-point ss) (y-point es)))))
