(define (make-account balance password)
  (let ((count 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch input-pw m)
        (if (eq? input-pw password)
            (begin
              (set! count 0)
              (cond ((eq? m 'withdraw) withdraw)
                    ((eq? m 'deposit) deposit)
                    (else (error "Unknown request -- MAKE-ACCOUNT"
                                  m))))
            (lambda (amount)
              (begin
                (set! count (+ 1 count))
                (display "Incorrect password\n")
                (if (> count 7)
                  (display "calling the cops...")
                  (begin (display count) (display " times wrong password!")))))))
    dispatch))
