(define (even? n)
  (= (remainder n 2) 0))
(define (double n)
  (* n 2))
(define (halve n)
  (/ n 2))
(define (mul-iter product a b)
  (cond ((= b 0) product)
        ((even? b) (mul-iter product (double a) (halve b)))
        (else (mul-iter (+ product a) a (- b 1)))))
(define (fast-mul a b)
  (mul-iter 0 a b))
